### ISSUE TITLE
You should not use <Route> outside a <Router>

### ISSUE THREAD

**Issue by austsinovich** [supasate/connected-react-router#295]
After update react-router to version 5.0.0 and connectedReactRouter to version 6.4.0 still having an error in console:
Error: Invariant failed: You should not use <Route> outside a <Router>

**Comment by bugzpodder** [comment]
I've ran into this issue before, make sure your react-router and react-router-dom are the same version (5.0) do a npm cache clean or yarn cache clean, remove node_modules and package-lock.json/yarn.lock and do a npm install/yarn install.

**Comment by ahmedtehseen** [comment]
@austsinovich have you found any solution to this problem?

**Comment by akomm** [comment]
@ahmedtehseen 

To sum it up, the whole concept behind NPM is broken to the bone (and using yarn on top of the same broken concept does not fix it).

You need to resolve dependencies yourself over multiple packages checking their peer dependencies (did not get any warning from npm/yarn, I know why, its just plain stupid, but lets not mess with it here).

yarn add react-router-dom@^4.3.1 react-router@^4.3.1 react@^16.4.0 connected-react-router@^6.3.2 redux@^4.0.1 react-redux@^6.0.1

I found scooping code and package.json's that this versions do match together and work. It fixed the issue for me.

**Comment by akomm** [comment]
@ahmedtehseen 

Stupidity of peer dependency system, where the system fails to realize there is an issue due to lax version requirements. In my case react-router was installed as ^4.3.1 and react-router-dom was installed as ^5.0.0. 

`yarn add react-router-dom@^4.3.1` 

fixed it.

However the mismatch can be anywhere for you, you could run this if that matches your other requirements, this combination works:

```
yarn add \
  react-router-dom@^4.3.1 \
  react-router@^4.3.1 \
  react@^16.4.0 \
  connected-react-router@^6.3.2 \
  redux@^4.0.1 \
  react-redux@^6.0.1
```

**Comment by murugaratham** [comment]
i tried clearing out and reinstalling, but it's still not working, changed `react-router-dom to: "4.3.1"` works

**Comment by akomm** [comment]
yes. even though react-router-dom ^4.3.1 depends on react-router ^4.3.1, npm decides its funny to install react-router-dom 5.0.0, even though you already have react-router ^4.3.1 installed. A normal package manager would find out that ^4.3.1 is the only matching package version, however npm is not a normal package manager.

I know of no package manager with that many stupid upside down behaviors as npm (not rust, not php, not java, not anything). Yeah but its always some super smart logical reason why that has to do upside down. Like the stupid lockfile behavior. Usually excused because "it was always like that, we want bc, but we created a new executable, which does as you expect", introducing thereby other issues which would never have existed in first place if simply being logical.
