### ISSUE TITLE
Cannot find module: 'lodash.isequalwith'.

### ISSUE THREAD

**Issue by tykdn** [supasate/connected-react-router#480]
When run npm install ,Failed to compile.
> ./node_modules/connected-react-router/esm/ConnectedRouter.js
Cannot find module: 'lodash.isequalwith'. Make sure this package is installed.

connected-react-router version is 6.9.0.

![image](https://user-images.githubusercontent.com/18005061/108678404-ffc0d780-7525-11eb-932d-8fa70ba66837.png)

Module ***lodash.isequal*** should be  in dependencies rathe than devDependencies?

**Comment by yolo2013** [comment]
+1

**Comment by Ivocin** [comment]
Same with you, now lodash.isequalwith  is in devDependencies and peerDependencies. 
I think a lot users will come across this error today.
You can add it as dependencies in your package.json as a temporary solution.

**Comment by ltnscp9028** [comment]
I made a PR and passed the test. Hopefully it will be merged soon.

**Comment by blinkcat** [comment]
May be a disaster

**Comment by ltnscp9028** [comment]
> May be a disaster

I think so. The relevant PR must be merged urgently. 
Errors may occur in the production environment.

**Comment by liorbentov** [comment]
> Same with you, now lodash.isequalwith is in devDependencies and peerDependencies.
> I think a lot users will come across this error today.
> You can add it as dependencies in your package.json as a temporary solution.

Yeap.. Already came across this one...
For now, I have set the version to be a fixed version(6.8.0) 🤷

**Comment by ssanri** [comment]
somebody just ruined monday...

**Comment by swapna-purohit-mpf** [comment]
please can the fix be merged soon? we are blocked with this.

**Comment by sachin-agarwal-by** [comment]
can we merged this urgently as we have already upgraded to latest version and build is failing.

**Comment by jebrii** [comment]
For now, you can change the dependency entry in your `package.json` to `"connected-react-router": "6.8.0"` (notice there's no `^` carrot in the version)

**Comment by supasate** [comment]
Should be fixed in v6.9.1.

**Comment by danielweck** [comment]
Thanks :)

```
    ERROR in ./node_modules/connected-react-router/esm/ConnectedRouter.js
    Module not found: Error: Can't resolve 'lodash.isequalwith' in 'node_modules/connected-react-router/esm'
     @ ./node_modules/connected-react-router/esm/ConnectedRouter.js 29:0-45 82:192-203
     @ ./node_modules/connected-react-router/esm/index.js
```

**Comment by LennyLip** [comment]
> Should be fixed in v6.9.1.

I got this issue with last versions lodash and connected-react router

**Comment by allengordon011** [comment]
I am still getting an error from this dependency when attempting to install connected-react-router v6.9.1
```
npm ERR! code E404
npm ERR! 404 Not Found - GET https://<private npm registry>/lodash.isequalwith - no such package available
npm ERR! 404 
npm ERR! 404  'lodash.isequalwith@^4.4.0' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'connected-react-router'

**Comment by vicodinvic1** [comment]
> > Should be fixed in v6.9.1.
> 
> @supasate I've got this issue with the last versions lodash and connected-react router
> 
> ![image](https://user-images.githubusercontent.com/955994/115365152-c8d90c00-a1cc-11eb-96f2-fc475ce26514.png)
> 
> ps. "name": "lodash.isequalwith", "version": "4.4.0",
> 
> **update**. Ok, it seems this is rollup named expost issue.

Hey, did you resolve the issue? You said it is rollup fault, I'm trying to build a prod build with Vite (it uses rollup under the hood) and it fails with mentioned error

**Comment by LennyLip** [comment]
> Hey, did you resolve the issue? You said it is rollup fault, I'm trying to build a prod build with Vite (it uses rollup under the hood) and it fails with mentioned error

https://stackoverflow.com/a/45535902/1271271

**Comment by vicodinvic1** [comment]
> > Hey, did you resolve the issue? You said it is rollup fault, I'm trying to build a prod build with Vite (it uses rollup under the hood) and it fails with mentioned error
> 
> https://stackoverflow.com/a/45535902/1271271

I already use @rollup/plugin-commonjs plugin and it doesn't resolve the issue

**Comment by LennyLip** [comment]
> I already use @rollup/plugin-commonjs plugin and it doesn't resolve the issue

Do you include lodash?
